name: Deploy Libro
on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necesario para poder hacer push de vuelta

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.1'

      - name: Generate Files with Go
        run: go run generate_summary.go

      # --- NUEVO PASO: COMMIT Y PUSH ---
      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md SUMMARY.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "docs: auto-update index [skip ci]" && git push)
      # ---------------------------------

      - name: Install mdBook
        run: |
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.37/mdbook-v0.4.37-x86_64-unknown-linux-gnu.tar.gz | tar -xz
          sudo mv mdbook /usr/local/bin/
          
      - name: Build Book
        run: mdbook build
        
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./book
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
